kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: argocd-secret
  namespace: argocd
  creationTimestamp: null
spec:
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
    type: Opaque
  encryptedData:
    dex.github.clientId: AgA5wunhzUeGItwDWfTYDeOQctJr3C8/fTvEfA3B8QZ5S7SlyeJPTeQ0RlklOwZx/HJd34QmCB8kd9OtVSNYTJCbjvBjvLInCI4nxRd8jYPkJe4XXXfTCKxboXy8EIGhOJBDFHXnRRKDd/r4LZxWk+x4JXhv1gma+S5jSuUODi2yO3UNk8jKUoHDKf4CsVh4c4jWICIokk5JlW3+hZYbgpN7KPemVi3tyTWf0T7wi+/2yFzg1KD4+4WK2+UmyJ4h0sSU2aTMcFz+/+HdzlxxiJN3oxCmRuNwX+xzHjvKZYdWZwroDpxpUxHayIJHYW4NArqQz2PqKdcCWuIbHgm7Rp2pywNF2jRwRaxPYA8T1JX7JaLCTzBHCFQ8PSro5uZpXJ4iUFOuu6xRNEND8xj/VG6Gw0kC/SWwQccsu1wS31+ns66od4fJq8Xt8rFL4/KNSjuRGNAhAlULItp/PyYNYUWvxU11/5t3em/5IJaux+KMtTa55rSzXWGLt6/jfUbGY8MNvSvPaNcd1fBi+ftjhNNs1z+WtYnYYqV7DD7wkDC/GTOKNYaqb8W111vFnybb13YCuI615s7GYMisr4b2yLJz7SdqE9ql69vxfVNU0BEgXIjOWVT9ezu6Nzm0h94Htra6DHKloqE1ObKuTYcyUtWHfXV/QHZQgimzda1s+bJGGVSJgNYeSPhrE9tLxe4uhXVdcy71Hxtn9eqBAItvat/A2T9ytg==
    dex.github.clientSecret: AgCN0g6JowiK4Thsd0EgjHWSBoFv8iCHF3iPtN2nCL9Rgp8mDsrr5UWwDtQRuoxZ0g7Hs1TsyVV55u7dBtkHtHqQotXLj+hoa1MUMMnbVqJRjB0KcDbLsFtY5TJjMU4N8Mnfh/uvn6qrEpdZmVVN333HdVGdoJEe/WxxbaomJxRXv6DQi3nqKYhD8Lr8DFjIeXJriGOzTy0DHgZfPgewZCxwZtDutfGtNTkhWq8ZVl6cC1+TiH8XSK65peQIbpsNlmADcsYA92OaGM2ZumOgNAV9KaSVm1HWrMiDXl6kBfUNK98FJwM7Ur5m9clnMOLIPBth2Jq7HAM30PaEII7JFdpNTmiE6hyfLVVdweFN1kYIg/Seg6ABNNPYadd3EwWNgs190bmxGDcin2OaZHPjiKCCYwRrQWy9qbeys8RfPkDoMA9WUMMJ/sm+C8PinQ1pAt6LLi1FhdifTI1kcfqElGTNQHGpIwMD2CUAQNg+c8p1lADwtNOMOz7dIUjdRLdPnC2RafKw1iHFG6wNV8jicapF9agng0E+7MAXJqNI3m3jEfqdPk/HcWKJS6AF2LnhTR/sZiidPCdPbEMwbfh8J24USBj5PbddKFmGxkcE2/mxkh421veqO8W7LKBJdYh9CvLCuvlWH68VXd9tQr+UctHZS0CjUhky7StRwwL2tOprlSNepzYZeG3Zj8o4a5n/BXP81O685dsL94+qaBR72I391wKX3Bva1nsbMzXYXcPdszW90BlSJlBw
