apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: home
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.13.2
    path: argocd/kube-system/sealed-secrets
    chart: sealed-secrets
    helm:
      parameters:
        - name: NAMESPACE
          value: sealed-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    syncoptions:
      - CreateNamespace=true
