apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: sealed-secrets
spec:
  project: home
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.13.2
    path: argocd/kube-system/sealed-secrets
    chart: sealed-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    syncoptions:
      - CreateNamespace=true
